In [1]:
"""Abbiamo una lista di liste: mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
Che tipo di struttura dati o matematica potrebbe rappresentare? 
Notare che tutte le liste "interne" sono della stessa dimensione
Come facciamo per accedere ad un elemento in particolare?"""
import numpy as np
import pandas as pd

mat = [[0, 1, 2, 3, 4],[5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
mat_array = np.array(mat)
mat_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
mat_array.shape

(3, 5)

In [5]:
mat_array[0,:]

array([0, 1, 2, 3, 4])

In [6]:
mat_array[-2,:]

array([5, 6, 7, 8, 9])

In [7]:
mat_array[1,2]

7

In [8]:
mat_array[-2,1::2]

array([6, 8])

In [9]:
mat_array[-2][::2]

array([5, 7, 9])

In [10]:
mat_df = pd.DataFrame(mat)
mat_df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14

In [11]:
"""Importiamo il modulo math e proviamo a usare le funzioni 
.sin() 
.cos() 
.factorial()
e la variabile 
.pi 
la riconoscete?"""
import math
x = math.sin(90)
x

0.8939966636005579

In [12]:
y = math.cos(90)
y

-0.4480736161291701

In [13]:
z = math.factorial(9)
z

362880

In [14]:
math.pi

3.141592653589793

In [15]:
"""Proviamo a eseguire 
math.degrees(math.pi)
Qual è e cosa significa il risultato?
Per saperne di più su questa funzione possiamo usare 
help(math.degrees"""
math.degrees(math.pi)

180.0

In [16]:
help(math.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [17]:
"""L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: 
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
trasformiamola in un array NumPy (casting): 
lst = np.array(lst)
e rispondiamo alle domande del CEO della Object SpA:
• qual è stata la vendita massima mensile? E quella minima?
• quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono? 
• quali sono le vendite minori di 3000 oggetti? 
• in media quanti oggetti sono stati venduti al mese?"""
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
import numpy as np
my_array = np.array(lst)
my_array

array([2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100,
       5350])

In [18]:
massimo = np.max(my_array)
massimo

8150

In [19]:
minimo = np.min(my_array)
minimo

1280

In [20]:
vendite_maggiori_di_4999 = my_array[my_array > 4999]
vendite_maggiori_di_4999

array([5500, 7200, 6410, 8150, 7100, 5350])

In [21]:
numero_vendite = len(vendite_maggiori_di_4999)
numero_vendite

6

In [22]:
vendite_minori_di_3000 = my_array[my_array < 3000]
vendite_minori_di_3000

array([2000, 1280, 1900, 2500])

In [23]:
media = np.mean(my_array)
media

4634.166666666667

In [24]:
"""Consideriamo il seguente dizionario:
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
Consideriamo ora la seguente Series:
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000],
                             index=range(1997, 2005))
Possiamo accedere alle stesse informazioni nello stesso modo:
fatturati_dict[1997] fatturati_series[1997]
Dunque qual è la differenza tra i due tipi di dato? 
Cosa potremmo fare con la Series che non possiamo fare con il dizionario?"""
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
fatturati_dict

{1997: 12000,
 1998: 15000,
 1999: 20000,
 2000: 23000,
 2001: 25000,
 2002: 17000,
 2003: 14000,
 2004: 21000}

In [25]:
print(type(fatturati_dict))

<class 'dict'>


In [26]:
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000],
                             index=range(1997, 2005))
fatturati_series

1997    12000
1998    15000
1999    20000
2000    23000
2001    25000
2002    17000
2003    14000
2004    21000
dtype: int64

In [27]:
print(type(fatturati_series))

<class 'pandas.core.series.Series'>


In [28]:
fatturati_dict[1997]

12000

In [29]:
fatturati_series[1997]

12000

In [30]:
fatturati_series.max()

25000

In [31]:
fatturati_series[fatturati_series.between(15000, 20000)]

1998    15000
1999    20000
2002    17000
dtype: int64

In [ ]:
"""Esercizio L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti,
memorizzato in un ndarray:
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] ) 
L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi: 
• con un ciclo for 7
• con il masking"""

In [32]:
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] ) 
stipendi

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [33]:
lista_stipendi_raddoppiati = []
for stipendio in stipendi:
    lista_stipendi_raddoppiati.append(stipendio * 2)
lista_stipendi_raddoppiati    

[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]

In [34]:
lista_stipendi_raddoppiati_numpy = stipendi * 2
lista_stipendi_raddoppiati_numpy

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])